parameters:
    ezobject_wrapper.ezobject_wrapper_factory.class: eZObject\WrapperBundle\Core\eZObjectWrapperFactory

services:
    ezobject_wrapper.services.factory:
        class: %ezobject_wrapper.ezobject_wrapper_factory.class%
        arguments: [@service_container]
    twig.extension.eZObjectWrapper:
        class: eZObject\WrapperBundle\Twig\eZObjectWrapperExtension
        arguments: [@ezpublish.controller.content.view]
        lazy: true
        tags:
            - { name: twig.extension }